"""add timeentry and breakperiod tables with cascade delete

Revision ID: 080379f9a116
Revises: b9948eddaec6
Create Date: 2025-07-22 14:45:24.610178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080379f9a116'
down_revision: Union[str, None] = 'b9948eddaec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timesheet_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('in_time', sa.Time(), nullable=False),
    sa.Column('out_time', sa.Time(), nullable=False),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('breakperiod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_entry_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['time_entry_id'], ['timeentry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breakperiod')
    op.drop_table('timeentry')
    # ### end Alembic commands ###
