"""remove hours_json from timesheet

Revision ID: 59e21cf8f7aa
Revises: 080379f9a116
Create Date: 2025-07-22 15:05:38.688466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e21cf8f7aa'
down_revision: Union[str, None] = '080379f9a116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timesheet', 'hours_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timesheet', sa.Column('hours_json', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
