"""add_manager_email_to_timeoff

Revision ID: 7ba4c7cb9a47
Revises: normalize_timesheetstatus_enum
Create Date: 2025-07-23 02:23:04.212385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba4c7cb9a47'
down_revision: Union[str, None] = 'normalize_timesheetstatus_enum'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeoff', sa.Column('manager_email', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timesheet', 'status',
               existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='timesheetstatus'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('timeoff', 'manager_email')
    # ### end Alembic commands ###
