"""Add project field to timesheet

Revision ID: b9948eddaec6
Revises: 198485ee8e3d
Create Date: 2025-07-21 16:19:00.026099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9948eddaec6'
down_revision: Union[str, None] = '198485ee8e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timesheet', sa.Column('project', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timesheet', 'project')
    # ### end Alembic commands ###
