"""Add password_hash and is_active to Employee model

Revision ID: d5fdd1dc2204
Revises: 8614dae2c2ac
Create Date: 2025-07-20 17:42:49.894508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd5fdd1dc2204'
down_revision: Union[str, None] = '8614dae2c2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('employee', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('employee', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('employee', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('employee', 'is_active')
    op.drop_column('employee', 'password_hash')
    op.drop_column('employee', 'full_name')
    # ### end Alembic commands ###
