"""add_submitted_status_and_submitted_at_field

Revision ID: e0dd256979c2
Revises: 59e21cf8f7aa
Create Date: 2025-07-22 17:47:36.729440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0dd256979c2'
down_revision: Union[str, None] = '59e21cf8f7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timesheet', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timesheet', 'submitted_at')
    # ### end Alembic commands ###
